set JAVA_HOME=C:\Program Files\Java\jdk1.8.0_40
set NETBEANS_HOME=D:\Program Files\NetBeans 8.0.2
set GLASSFISH_HOME=D:\Program Files\glassfish-4.1
set MYSQL_HOME=D:\Program Files\MySQL\MySQL Server 5.6
set MYSQL_ROOT_PASSWORD=password
set MYSQL_HOME=%MYSQL_HOME%\bin\mysql
set ANT_HOME=%NETBEANS_HOME%\extide\ant
set PATH=%PATH%;
set PATH=%PATH%%JAVA_HOME%\bin;
set PATH=%PATH%%ANT_HOME%\bin;